// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Web için kontrol
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }
  
  // Web Firebase Config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5EvynualJEwE9oTcXlLN0JpmNyt33Amw',
    appId: '1:568696463280:web:d87153ee39b164667a4075',
    messagingSenderId: '568696463280',
    projectId: 'bir-adim-umut-yeni',
    authDomain: 'bir-adim-umut-yeni.firebaseapp.com',
    storageBucket: 'bir-adim-umut-yeni.firebasestorage.app',
    measurementId: 'G-8VVERCBKFQ',
  );

  // Android Firebase Config - Firebase Console'dan aldığınız bilgilerle değiştirin
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3u8jK6JuL7BIllbBU7FuZgkftptpYwEI',
    appId: '1:568696463280:android:1c990d871261632e7a4075',
    messagingSenderId: '568696463280',
    projectId: 'bir-adim-umut-yeni',
    storageBucket: 'bir-adim-umut-yeni.firebasestorage.app',
  );

  // iOS Firebase Config - Firebase Console'dan aldığınız bilgilerle değiştirin
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3u8jK6JuL7BIllbBU7FuZgkftptpYwEI',
    appId: '1:568696463280:ios:abcdef123456789',
    messagingSenderId: '568696463280',
    projectId: 'bir-adim-umut-yeni',
    storageBucket: 'bir-adim-umut-yeni.firebasestorage.app',
    iosBundleId: 'com.example.birAdimUmut',
  );
}

/*
FIREBASE SETUP TALIMATARI:

1. Firebase Console'da proje oluştur:
   https://console.firebase.google.com
   
2. Android için google-services.json indir:
   - Android Studio'da Tools > Firebase > Connect
   - android/app/ klasörüne koy
   
3. iOS için GoogleService-Info.plist indir:
   - iOS proje ayarlarında Authentication'ı aktifleştir
   - ios/Runner/GoogleService-Info.plist olarak kaydet
   
4. .env dosyası oluştur (.gitignore'a ekle):
   FIREBASE_API_KEY=xxx
   FIREBASE_APP_ID=xxx
   FIREBASE_MESSAGING_SENDER_ID=xxx
   FIREBASE_PROJECT_ID=xxx
   FIREBASE_AUTH_DOMAIN=xxx
   FIREBASE_STORAGE_BUCKET=xxx
   
5. pubspec.yaml'da flutter_dotenv ekle:
   dependencies:
     flutter_dotenv: ^5.1.0
     
6. main.dart'da şu kodu ekle:
   await dotenv.load();
   
ÖNEMLI: Hiçbir API key'i commit etme!
*/
